# Generated by Django 4.0.6 on 2022-09-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
